#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Only takes the class name"
    exit 1
fi

cat <<EOF >> include/$1.hpp
class $1 {
public:
    $1();
};
EOF

cat <<EOF >> src/$1.cpp 
#include "$1.hpp"

$1::$1(){}
EOF

echo "Class $1 created."